### ISSUE TITLE
Refine Roadmap and Contributor Onboarding Experience

### ISSUE THREAD

**Issue by titusrobin** [nogibjj/candle-cookbook#7]
## Goal
The aim of this issue is to refine the contributor onboarding process to ensure it's intuitive and welcoming for newcomers at various levels of experience. 

Lets identify and smooth out any confusing aspects of the current userflow and establish a clear, step-by-step map that can facilitate a better understanding and engagement with our project.

## Objectives
1. **Clear Onboarding Pathways:**
   - Create intuitive, goal-oriented onboarding flows that offer precise guidance for new contributors.
   - Enable contributors to easily navigate our system and articulate project details when sharing with others.

2. **Continuous Feedback Integration:**
   - Implement a Kaizen-inspired system that regularly solicits and integrates contributor feedback to refine the userflow.

## Proposed Action Items
- [ ] Establish a UI/UX standard for the Candle Cookbook project.
- [ ] Consider developing a survey or feedback mechanism to gather contributors' experiences.
- [ ] Design an onboarding map to address identified issues and to clarify the path forward.
- [ ] Integrate the new onboarding guide within the Contributor Guidelines.

## Additional Notes
I've attached a Miro board(WIP) screenshot that outlines the initial thoughts on the userflow and areas that may require attention. This visual aid can serve as a starting point for discussion and brainstorming on how to enhance our onboarding experience.

[View the Miro Board here](https://miro.com/welcomeonboard/RnNycHNLUllkMFg4Q2E3RmdEVDJFcEsxUXJNOVZRR01SS2xBRTJwMzlaQ3QxM01DcDI1c1k1dGJ3RmMxNk5XYnwzNDU4NzY0NTY0ODQ2ODI1ODk5fDI=?share_link_id=650731889748)
<img width="888" alt="Screenshot 2023-11-11 at 2 20 06 PM" src="https://github.com/nogibjj/candle-cookbook/assets/143838819/2fe93c00-a778-47c0-beca-e85431354e69">
